AWSTemplateFormatVersion: 2010-09-09
Description: Magistum Serverless PHP 7.3.1
Resources:
  ArrayStats:
    Properties:
      CodeUri: s3://magistum-sam/539b4fe0df7166cc04e0104df34a7449
      Description: This is the statistics function thas calculates payload array.
      FunctionName:
        Fn::Sub: ${AWS::StackName}-array-stats
      Handler: array.stats
      Layers:
      - Fn::Sub: arn:aws:lambda:eu-central-1:303814004728:layer:aws-lambda-layer-php-7-3-1:6
      MemorySize: 128
      Runtime: provided
      Timeout: 4
      Tracing: Active
    Type: AWS::Serverless::Function
  HelloPhp73:
    Properties:
      CodeUri: s3://magistum-sam/539b4fe0df7166cc04e0104df34a7449
      Description: This is the hello world function from lambda php 7.3.1 layer
      FunctionName:
        Fn::Sub: ${AWS::StackName}-hello
      Handler: hello.hello
      Layers:
      - Fn::Sub: arn:aws:lambda:eu-central-1:303814004728:layer:aws-lambda-layer-php-7-3-1:6
      MemorySize: 128
      Runtime: provided
      Timeout: 4
      Tracing: Active
    Type: AWS::Serverless::Function
  Info:
    Properties:
      CodeUri: s3://magistum-sam/539b4fe0df7166cc04e0104df34a7449
      Description: This is the statistics function thas calculates payload array.
      FunctionName:
        Fn::Sub: ${AWS::StackName}-info
      Handler: array.info
      Layers:
      - Fn::Sub: arn:aws:lambda:eu-central-1:303814004728:layer:aws-lambda-layer-php-7-3-1:6
      MemorySize: 128
      Policies:
      - S3ReadPolicy:
          BucketName: magistum-sam
      Runtime: provided
      Timeout: 4
      Tracing: Active
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
