AWSTemplateFormatVersion: 2010-09-09
Description: Magistum Serverless Node.js
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-hello
      Description: This is the hello world function
      CodeUri: src
      Runtime: nodejs18.x
      Handler: hello.handler
      MemorySize: 128
      Timeout: 4
      Tracing: Active

  ArrayStats:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-array-stats
      Description: This is the statistics function that calculates payload array.
      CodeUri: src
      Runtime: nodejs18.x
      Handler: array.stats
      MemorySize: 128
      Timeout: 4
      Tracing: Active

  ItemAnalysis:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-item-analysis
      Description: This is the statistics function that calculates item analysis of payload object.
      CodeUri: src
      Runtime: nodejs18.x
      Handler: array.itemAnalysis
      MemorySize: 512
      Timeout: 16
      Tracing: Active

  Info:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-info
      Description: This is the info function that returns runtime information
      CodeUri: src
      Runtime: nodejs18.x
      Handler: array.info
      MemorySize: 128
      Timeout: 4
      Tracing: Active
      Policies:
        - S3ReadPolicy:
            BucketName: magistum-sam