AWSTemplateFormatVersion: 2010-09-09
Description: Magistum Serverless PHP 7.3.1
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloPhp73:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-hello
      Description: This is the hello world function from lambda php 7.3.1 layer
      CodeUri: src
      Runtime: provided
      Handler: hello.hello
      MemorySize: 128
      Timeout: 4
      Tracing: Active
      Layers:
        - 'arn:aws:lambda:eu-central-1:303814004728:layer:aws-lambda-layer-php-7-3-1:6'
  ArrayStats:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-array-stats
      Description: This is the statistics function thas calculates payload array.
      CodeUri: src
      Runtime: provided
      Handler: array.stats
      MemorySize: 128
      Timeout: 4
      Tracing: Active
      Layers:
        - 'arn:aws:lambda:eu-central-1:303814004728:layer:aws-lambda-layer-php-7-3-1:6'
  Info:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-info
      Description: This is the statistics function thas calculates payload array.
      CodeUri: src
      Runtime: provided
      Handler: array.info
      MemorySize: 128
      Timeout: 4
      Tracing: Active
      Layers:
        - 'arn:aws:lambda:eu-central-1:303814004728:layer:aws-lambda-layer-php-7-3-1:6'
      Policies:
        - S3ReadPolicy:
            BucketName: magistum-sam